language: php

sudo: required

php:
    - 5.6
    - 5.5
    - 5.4

compiler:
    - gcc

before_script:
    - git submodule update --init
script:
    - phpize
    - ./configure --with-libdir=lib/x86_64-linux-gnu --with-pcre-dir=/usr
    - echo "n" | make test
