language: php

sudo: required

php:
    - 5.6
    - 5.5
    - 5.4

compiler:
    - gcc

before_script:
    - ./.travis.scripts/compile.sh
script:
    - patch Makefile < .travis.scripts/Makefile.patch
    - echo "n" | make test
